title: NontonPilem
email: me@montonpilem.ml
#description: > # this means to ignore newlines until "baseurl:"
description: "Nonton Pilem Gratis? di sini aja"
baseurl:  # the subpath of your site, e.g. /blog
url: https://nontonpilem.ml
enforce_ssl: nontonpilem.ml
#twitter_username: easton042
#github_username:  easton042
#linkedin_username:  eastonlee

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - .sass-cache

safe: false

# easton
permalink: /blog/:year/:month/:title/

# minima theme, deprecated
show_downloads: false
# google_analytics: UA-58961104-2

# poole theme, being used, just need to modify font-size in _variables.scss
#html {
#  font-size: 14px;
#  line-height: 1.5;
#}
#@media (min-width: 38em) {
#  html {
#    font-size: 20px;
#  }
#}
tagline: experientialism
paginate:            1
sass:
  sass_dir:          _sass
  style:            :compressed
author: Pilem

# analytics_id: UA-58961104-2

# disqus:
  shortname: eastonlee

excerpt_separator: <!--more-->
